// generated by calc_pids.py
const uint32_t obd2_query_sequence[] = {
    PID_HV_AMPS,                   //  0 X
    PID_MGB_AMPS,                  //  1     X
    PID_MGA_AMPS,                  //  2         X
    PID_HV_VOLTS,                  //  3             X
    PID_MGB_VOLTS,                 //  4                 X
    PID_HV_AMPS,                   //  5 X
    PID_MGB_AMPS,                  //  6     X
    PID_MGA_AMPS,                  //  7         X
    PID_EV_RANGE_REM,              //  8                     X
    PID_MGA_VOLTS,                 //  9                         X
    PID_HV_AMPS,                   // 10 X
    PID_MGB_AMPS,                  // 11     X
    PID_MGA_AMPS,                  // 12         X
    PID_HV_VOLTS,                  // 13             X
    PID_MGB_VOLTS,                 // 14                 X
    PID_HV_AMPS,                   // 15 X
    PID_MGB_AMPS,                  // 16     X
    PID_MGA_AMPS,                  // 17         X
    PID_BATTERY_SOC,               // 18                             X
    PID_INTAKE_TEMP,               // 19                                 X
    PID_HV_AMPS,                   // 20 X
    PID_MGB_AMPS,                  // 21     X
    PID_MGA_AMPS,                  // 22         X
    PID_HV_VOLTS,                  // 23             X
    PID_MGB_VOLTS,                 // 24                 X
    PID_HV_AMPS,                   // 25 X
    PID_MGB_AMPS,                  // 26     X
    PID_MGA_AMPS,                  // 27         X
    PID_AIR_PRESSURE,              // 28                                     X
    PID_BATTERY_TEMP,              // 29                                         X
    PID_HV_AMPS,                   // 30 X
    PID_MGB_AMPS,                  // 31     X
    PID_MGA_AMPS,                  // 32         X
    PID_HV_VOLTS,                  // 33             X
    PID_MGB_VOLTS,                 // 34                 X
    PID_HV_AMPS,                   // 35 X
    PID_MGB_AMPS,                  // 36     X
    PID_MGA_AMPS,                  // 37         X
    PID_EV_RANGE_REM,              // 38                     X
    PID_MGA_VOLTS,                 // 39                         X
    PID_HV_AMPS,                   // 40 X
    PID_MGB_AMPS,                  // 41     X
    PID_MGA_AMPS,                  // 42         X
    PID_HV_VOLTS,                  // 43             X
    PID_MGB_VOLTS,                 // 44                 X
    PID_HV_AMPS,                   // 45 X
    PID_MGB_AMPS,                  // 46     X
    PID_MGA_AMPS,                  // 47         X
    PID_BATTERY_RAW_SOC,           // 48                                             X
    PID_COOLANT_TEMP,              // 49                                                 X
    PID_HV_AMPS,                   // 50 X
    PID_MGB_AMPS,                  // 51     X
    PID_MGA_AMPS,                  // 52         X
    PID_HV_VOLTS,                  // 53             X
    PID_MGB_VOLTS,                 // 54                 X
    PID_HV_AMPS,                   // 55 X
    PID_MGB_AMPS,                  // 56     X
    PID_MGA_AMPS,                  // 57         X
    PID_TROUBLECODE_QUERY,         // 58                                                     X
    PID_BATTERY_TEMP,              // 59                                         X
    0
};

const uint32_t obd2_query_sequence_low[] = {
    PID_HV_AMPS,                   //  0
    PID_MGB_AMPS,                  //  1
    PID_HV_VOLTS,                  //  2
    PID_MGB_VOLTS,                 //  3
    PID_MGA_AMPS,                  //  4
    PID_EV_RANGE_REM,              //  5
    PID_MGA_VOLTS,                 //  6
    PID_BATTERY_SOC,               //  7
    PID_BATTERY_RAW_SOC,           //  8
    PID_INTAKE_TEMP,               //  9
    PID_COOLANT_TEMP,              // 10
    PID_BATTERY_TEMP,              // 11
    PID_TROUBLECODE_QUERY,         // 12
    PID_AIR_PRESSURE,              // 13
    0
};
