// generated by calc_pids.py
        case PID_HV_AMPS & 0xFFFF:
            cd.hv_amps = vab;
            break;
        case PID_MGB_AMPS & 0xFFFF:
            cd.mgb_amps = vab;
            break;
        case PID_HV_VOLTS & 0xFFFF:
            cd.hv_volts = vab;
            break;
        case PID_MGB_VOLTS & 0xFFFF:
            cd.mgb_volts = vab;
            break;
        case PID_MGA_AMPS & 0xFFFF:
            cd.mga_amps = vab;
            break;
        case PID_EV_RANGE_REM & 0xFFFF:
            cd.ev_range_rem = vab;
            break;
        case PID_MGA_VOLTS & 0xFFFF:
            cd.mga_volts = vab;
            break;
        case PID_BATTERY_SOC & 0xFFFF:
            cd.battery_soc = va;
            break;
        case PID_BATTERY_RAW_SOC & 0xFFFF:
            cd.battery_raw_soc = va;
            break;
        case PID_INTAKE_TEMP & 0xFFFF:
            cd.intake_temp = va;
            break;
        case PID_COOLANT_TEMP & 0xFFFF:
            cd.coolant_temp = va;
            break;
        case PID_BATTERY_TEMP & 0xFFFF:
            cd.battery_temp = va;
            break;
        case PID_AIR_PRESSURE & 0xFFFF:
            cd.air_pressure = va;
            break;
